### ISSUE TITLE
Tarea practica de ejercicios básicos (suma, resta, multiplicación y división) Edwin Lopez Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Edwin14459#1]
[Practica de ejercicios básicos suma, resta, multiplicación y división.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Edwin14459/files/7151946/Practica.de.ejercicios.basicos.suma.resta.multiplicacion.y.division.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación de acuerdo a rúbrica

**Comment by josealfredo79** [comment]
Falta la calificación

**Comment by UrielGB10** [comment]
Compañero te pongo un 15% por algunos detalles que tuviste

**Comment by josealfredo79** [comment]
Bien hecho y revisado
